### ISSUE TITLE
The package is not working on Sublime text 3126

### ISSUE THREAD

**Issue by Hujjat** [redgluten/laravel_forms_boostrap_snippets#7]
I have installed this package using package control, But it's not working with I use shortcuts. I have the latest version of Sublime text. 

I search the packages directory, but I could't find any folder or file for t his package after installing. Now, when I search on package control to reinstall, I can't find it as if it's install. But nothing work. Please help me what is wrong.

Thanks' :)

**Comment by roni-estein** [comment]
I haven't tried it yet, but have you tried just adding the git repo source to your /User directory? That should work.

**Comment by redgluten** [comment]
Sorry I did not have the time to look at it. Do you have [laravel-blade](https://github.com/Medalink/laravel-blade) installed?

**Comment by redgluten** [comment]
Please try the latest release and let me know if it works for you.

**Comment by Hujjat** [comment]
Hi, I have installed the latest version. Still not working. Autocomplete is not working :(

**Comment by redgluten** [comment]
Again do you have the syntax [laravel-blade](https://github.com/Medalink/laravel-blade) installed?

**Comment by Hujjat** [comment]
@redgluten Nop, I don't have that package.

**Comment by redgluten** [comment]
@Hujjat Can you try installing it and see if that helps (please restart Sublime Text in between)? Are you using another syntax highlighter for Blade at the moment?

**Comment by Hujjat** [comment]
@redgluten That worked. 👍 After installing Laravel Blade, it's working now.

**Comment by redgluten** [comment]
Ok thanks for confirming, I will update the README.
