### ISSUE TITLE
Typo on Package Control

### ISSUE THREAD

**Issue by christopherarter** [redgluten/laravel_forms_boostrap_snippets#8]
Not a huge deal, just wanted to let you know on the trigger docs on Package Control you swapped text and textarea. just a heads up!

**Comment by redgluten** [comment]
Thanks! Fixed by [#01482b7a9430d13e68ef2a4198b27163192fcd62](https://github.com/redgluten/laravel_forms_boostrap_snippets/commit/01482b7a9430d13e68ef2a4198b27163192fcd62).
